version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC 
      - "4318:4318"    # OTLP HTTP 
    networks:
      - jaeger-net

networks:
  jaeger-net:
    driver: bridge
