auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h


compactor:
  working_directory: /loki/compactor
  compaction_interval: 5m
  retention_enabled: false


limits_config:
  allow_structured_metadata: true
  max_streams_per_user: 0
  ingestion_rate_mb: 100
  ingestion_burst_size_mb: 200
  per_stream_rate_limit: 100MB
  per_stream_rate_limit_burst: 200MB
  max_line_size: 10MB
  reject_old_samples: false
  reject_old_samples_max_age: 168h
  unordered_writes: true

 
ingester:
  chunk_idle_period: 30s
  chunk_target_size: 1536000
  max_chunk_age: 2h
  flush_check_period: 10s
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
    join_after: 0s